SCAME/Models/Consultorio.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SCAME.Models
{
    public class Consultorio
    {
        [Key]
        public int IdConsultorio { get; set; }
        [Column(TypeName = "nvarchar(100)")]
        [DisplayName("Imagen Promocional")]
        public string ImageName { get; set; }
        [NotMapped]
        [DisplayName("Subir Imagen Promocional:")]
        public IFormFile ImageFile { get; set; }
        [NotMapped]
        [DisplayName("Actualizar Imagen")]
        public IFormFile ImageFileNuevo { get; set; }
        public string Ruc { get; set; }
        [DisplayName("Nombre Consultorio")]
        public string NombreConsultorio { get; set; }
        [DisplayName("Cedula del Representante")]
        public string CedulaRepresentanteLegal { get; set; }
        [DisplayName("Nombre Representante")]
        public string NombreRepresentateLegal { get; set; }
        public string ApellidoRepresentanteLegal { get; set; }
        public string Direccion { get; set; }
        [DisplayName("Patente Municipal")]
        public string NumPatenteMunicipal { get; set; }
        [DisplayName("Permiso Funcionamiento MSP")]
        public string PermisoFuncionamientoMsp { get; set; }
        public List<Horario> Horarios { get; set; } = new List<Horario>();
        public List<Medico> Medico { get; set; }
        [NotMapped]
        public Medico Medicos { get; set; }
        public int CantonId { get; set; }
        public Canton Canton { get; set; }
        public string UserId { get; set; }
        public IdentityUser User { get; set; }
        public List<MedicoDetalle> MedicoDetalles { get; set; }
        [NotMapped]
        public MedicoDetalle MedicoDetalle { get; set; }
        public bool Estado { get; set; } = true;
    }
}

SCAME/Controllers/CitasController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SCAME.Data;
using SCAME.Models;

namespace SCAME.Controllers
{
    public class CitasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private UserManager<IdentityUser> userManager;


        public CitasController(ApplicationDbContext context, UserManager<IdentityUser> userMgr)
        {
            _context = context;
            this.userManager = userMgr;
        }

        // GET: Citas
        public async Task<IActionResult> Index()
        {
            var user = await userManager.GetUserAsync(User);
            var listPaciente = await _context.Paciente.Where(p => p.UserId == user.Id).ToListAsync();
            var listConsultorio = await _context.Consultorio.Where(p => p.UserId == user.Id).ToListAsync();


            if (listPaciente.Count()>0)
            {
                var applicationDb = _context.Cita.Include(c => c.Especialidad).Include(c => c.HorasAtencion).Include(c => c.Medico).Include(c => c.Consultorio).Include(c => c.Paciente).Where(c => c.PacienteId == listPaciente[0].IdPaciente);
                return View(await applicationDb.ToListAsync());
            }
            var applicationDbContext = _context.Cita.Include(c => c.Especialidad).Include(c => c.HorasAtencion).Include(c => c.Medico).Include(c => c.Consultorio).Include(c => c.Paciente).Where(c => c.ConsultorioId == listConsultorio[0].IdConsultorio);
            return View(await applicationDbContext.ToListAsync());

        }

        // GET: Citas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita
                .Include(c => c.Especialidad)
                .Include(c => c.HorasAtencion)
                .Include(c => c.Paciente)
                .Include(c=> c.Medico)
                .Include(c=>c.Consultorio)
                .FirstOrDefaultAsync(m => m.IdCita == id);
            if (cita == null)
            {
                return NotFound();
            }

            return View(cita);
        }

        // GET: Citas/Create
        public IActionResult Create(int idC, int idM, int idE)
        {

            var detalle = _context.MedicoDetalle.Where(d => d.ConsultorioId == idC).ToList();
            ViewData["ConsultorioId"] = idC;
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "NombreEspecialidad");


            ViewData["HorasAtencionId"] = new SelectList(_context.HorasAtencion.Where(ha => ha.Disponibilidad == true && ha.Turno.ConsultorioId == idC), "IdHorasAtencion", "HoraInicio");
            return View();

        }

        public JsonResult MedicoSelect(int IdEspecialidad)
        {
            List<ElementJsonIntKey> lst = new List<ElementJsonIntKey>();
            lst = (from db in _context.Medicos
                   where db.Detalle.EspecialidadId == IdEspecialidad
                   select new ElementJsonIntKey
                   {
                       Value = db.Id,
                       Text = db.Nombre + db.Apellido
                   }).ToList();

            return Json(lst);
        }

        public class ElementJsonIntKey
        {
            public int Value { get; set; }
            public string Text { get; set; }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FechaCita,MedicoId,MotivoCita,EspecialidadId,ConsultorioId,HorasAtencionId")] Cita cita)
        {
            var user = await userManager.GetUserAsync(User);
            if (ModelState.IsValid)
            {

            
            var listPaciente = await _context.Paciente.Where(p=>p.UserId == user.Id).ToListAsync();
            var horadisponible = await _context.HorasAtencion.Where(h => h.IdHorasAtencion == cita.HorasAtencionId).ToListAsync();

                foreach (var item in listPaciente)
            {
                    
                    cita.PacienteId = item.IdPaciente;
                    cita.EstadoCita = "Activa";
                    cita.Estado = true;
                    _context.Add(cita);
                    horadisponible[0].Disponibilidad = false;
                    _context.Update(horadisponible[0]);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
            }
            }
            return NotFound();
        }

        // GET: Citas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita.FindAsync(id);
            if (cita == null)
            {
                return NotFound();
            }
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Id", cita.EspecialidadId);
            ViewData["HorasAtencionId"] = new SelectList(_context.HorasAtencion, "IdHorasAtencion", "IdHorasAtencion", cita.HorasAtencionId);
            ViewData["PacienteId"] = new SelectList(_context.Paciente, "IdPaciente", "IdPaciente", cita.PacienteId);
            return View(cita);
        }

        // POST: Citas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCita,PacienteId,FechaCita,MedicoId,MotivoCita,MotivoAnulacion,EspecialidadId,ConsultorioId,HorasAtencionId,EstadoCita,Estado")] Cita cita)
        {
            if (id != cita.IdCita)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cita);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CitaExists(cita.IdCita))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Id", cita.EspecialidadId);
            ViewData["HorasAtencionId"] = new SelectList(_context.HorasAtencion, "IdHorasAtencion", "IdHorasAtencion", cita.HorasAtencionId);
            ViewData["PacienteId"] = new SelectList(_context.Paciente, "IdPaciente", "IdPaciente", cita.PacienteId);
            return View(cita);
        }

        // GET: Citas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cita = await _context.Cita
                .Include(c => c.Especialidad)
                .Include(c => c.HorasAtencion)
                .Include(c => c.Paciente)
                .FirstOrDefaultAsync(m => m.IdCita == id);
            if (cita == null)
            {
                return NotFound();
            }

            return View(cita);
        }

        // POST: Citas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cita = await _context.Cita.FindAsync(id);
            _context.Cita.Remove(cita);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CitaExists(int id)
        {
            return _context.Cita.Any(e => e.IdCita == id);
        }
    }
}

SCAME/Views/Consultorios/Create.cshtml
@model SCAME.Models.Consultorio

@{
    ViewData["Title"] = "Create";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}
    <div class="col-md-12">
        <br />
        <h1>Registro del consultorio</h1>
        <h4>Ingrese todo la información solicitada:</h4>
        

        <form asp-action="Create" enctype="multipart/form-data">
            <div class="form-row">
                <div class="col-md-3 mb-3">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="ImageFile" class="control-label"></label>
                        <input asp-for="ImageFile" accept="image/*" />
                        <span asp-validation-for="ImageFile" class="text-danger"></span>
                    </div>

                </div>
                <div class="col-md-3 mb-3">
                    <div class="form-group">
                        <label asp-for="Ruc" class="control-label"></label>
                        <input asp-for="Ruc" class="form-control" />
                        <span asp-validation-for="Ruc" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <div class="form-group">
                        <label asp-for="NombreConsultorio" class="control-label">Nombre Consultorio</label>
                        <input asp-for="NombreConsultorio" class="form-control" />
                        <span asp-validation-for="NombreConsultorio" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-row ">
                <div class="form-group col-md-3 mb-3">
                    <label asp-for="CedulaRepresentanteLegal" class="control-label">Cédula del representate legal</label>
                    <input asp-for="CedulaRepresentanteLegal" type="number" class="form-control" />
                    <span asp-validation-for="CedulaRepresentanteLegal" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4 mb-3">
                    <label asp-for="NombreRepresentateLegal" class="control-label">Nombres del representate legal</label>
                    <input asp-for="NombreRepresentateLegal" class="form-control" />
                    <span asp-validation-for="NombreRepresentateLegal" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4 mb-3">
                    <label asp-for="ApellidoRepresentanteLegal" class="control-label">Apellidos del representate legal</label>
                    <input asp-for="ApellidoRepresentanteLegal" class="form-control" />
                    <span asp-validation-for="ApellidoRepresentanteLegal" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-2 mb-3">
                    <label asp-for="CantonId" class="control-label">Selecciona tu ciudad</label>
                    <select asp-for="CantonId" class="form-control" asp-items="ViewBag.CantonId"></select>
                    <span asp-validation-for="CantonId" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6 mb-3">
                    <label asp-for="Direccion" class="control-label">Dirección</label>
                    <input asp-for="Direccion" class="form-control" />
                    <span asp-validation-for="Direccion" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-5 mb-3">
                    <label asp-for="NumPatenteMunicipal" class="control-label">Número de patente municipal</label>
                    <input asp-for="NumPatenteMunicipal" class="form-control" />
                    <span asp-validation-for="NumPatenteMunicipal" class="text-danger"></span>
                </div>
                <div class="form-group col-md-5 mb-3">
                    <label asp-for="PermisoFuncionamientoMsp" class="control-label">Número del permiso de funcionamiento otrogado por MSP</label>
                    <input asp-for="PermisoFuncionamientoMsp" class="form-control" />
                    <span asp-validation-for="PermisoFuncionamientoMsp" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row ">
                <div class="form-group col-md-2 mb-3">
                    <input type="submit" value="Siguiente" class="btn btn-primary" />
                </div>
                <div class="form-group col-md-7 mb-3"> </div>
                <div class="form-group col-md-2 mb-3">
                    <a class="nav-link" asp-area="Identity" asp-page="/Account/Manage/Index">Regresar</a>
                </div>
            </div>
        </form>
    </div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

SCAME/Views/Consultorios/Delete.cshtml
@model SCAME.Models.Consultorio

@{
    ViewData["Title"] = "Eliminar";
}

    <div class="col-md-12">
        <h1 class="h1 text-strong text-center padding">Eliminar <small>Consultorio</small></h1>
        <h3>¿Éstas seguro de eliminar? no se podrá recuperar la Información</h3>
        <hr />
        <div>
            <div class="form-row">
                <div class="col-md-1 mb-2">
                    <p class="form-group">Imagen</p>
                    <img src="@("/image/" + Model.ImageName)" asp-append-version="true" width="100px" height="100px" />
                </div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">@Html.DisplayNameFor(model => model.UserId)</p>
                    <label class="form-group">@Html.DisplayFor(model => model.UserId)</label>
                </div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">@Html.DisplayNameFor(model => model.Ruc)</p>
                    <label class="form-group"> @Html.DisplayFor(model => model.Ruc)</label>
                </div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">Nombre del Consultorio</p>
                    <label class="form-group"> @Html.DisplayFor(model => model.NombreConsultorio)</label>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-1 mb-2"></div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">Cédula del Representante Legal</p>
                    <label class="form-group">@Html.DisplayFor(model => model.CedulaRepresentanteLegal)</label>
                </div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">Nombre del Representate Legal</p>
                    <label class="form-group">
                        @Html.DisplayFor(model => model.NombreRepresentateLegal)
                        @Html.DisplayFor(model => model.ApellidoRepresentanteLegal)
                    </label>
                </div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">@Html.DisplayNameFor(model => model.User.PhoneNumber)</p>
                    <label class="form-group"> @Html.DisplayFor(model => model.User.PhoneNumber)</label>
                </div>

            </div>
            <div class="form-row">
                <div class="col-md-1 mb-2"></div>
                <div class="col-md-3 mb-2">
                    <p class="form-group">@Html.DisplayNameFor(model => model.User.Email)</p>
                    <label class="form-group">@Html.DisplayFor(model => model.User.Email)</label>
                </div>
                <div class="col-md-6 mb-2">
                    <p class="form-group"> Dirección</p>
                    <label class="form-group">@Html.DisplayFor(model => model.Direccion)</label>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-1 mb-2"></div>
                <div class="col-md-5 mb-2">
                    <p class="form-group">Patente Municipal</p>
                    <label class="form-group">@Html.DisplayFor(model => model.NumPatenteMunicipal)</label>
                </div>
                <div class="col-md-5 mb-2">
                    <p class="form-group">Permiso de Funcionamiento otorgado por el MSP</p>
                    <label class="form-group">@Html.DisplayFor(model => model.PermisoFuncionamientoMsp))</label>
                </div>
            </div>
            <div class="form-row ">
                <div class="form-group col-md-1 mb-3"></div>
                <div class="form-group col-md-2 mb-3">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="IdConsultorio" />
                        <input type="submit" value="Eliminar" class="btn btn-danger" />
                    </form>
                </div>
                <div class="form-group col-md-6 mb-3"> </div>
                <div class="form-group col-md-2 mb-3">
                    <a class="nav-link" asp-action="Index">Regresar</a>
                </div>
            </div>
            <br />
            <br />

        </div>
    </div>

SCAME/Views/Consultorios/Details.cshtml
@model SCAME.Models.Consultorio

@{
    ViewData["Title"] = "Detalle";
}

    <div class="col-md-12 text-dark">
        <h1 class="h1 text-strong text-center padding-2x">Detalles del <small>Consultorio</small></h1>
        <hr />
        <div class="form-row">
            <div class="col-md-1 mb-2"></div>
            <div class="col-md-3 mb-2">
                <p class="form-group ">Imagen</p>
                <img src="@("/Image/" + Model.ImageName)" asp-append-version="true" style=" width:40px; height:50px" />

            </div>
            <div class="col-md-3 mb-2">
                <p class="form-group">@Html.DisplayNameFor(model => model.Ruc)</p>
                <label class="form-group"> @Html.DisplayFor(model => model.Ruc)</label>
            </div>
            <div class="col-md-3 mb-2">
                <p class="form-group">Nombre del Consultorio</p>
                <label class="form-group"> @Html.DisplayFor(model => model.NombreConsultorio)</label>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-1 mb-2"></div>
            <div class="col-md-3 mb-2">
                <p class="form-group">Cédula del Representante Legal</p>
                <label class="form-group">@Html.DisplayFor(model => model.CedulaRepresentanteLegal)</label>
            </div>
            <div class="col-md-3 mb-2">
                <p class="form-group">Nombre del Representate Legal</p>
                <label class="form-group">
                    @Html.DisplayFor(model => model.NombreRepresentateLegal)
                    @Html.DisplayFor(model => model.ApellidoRepresentanteLegal)
                </label>
            </div>
            <div class="col-md-3 mb-2">
                <p class="form-group">Telefono</p>
                <label class="form-group"> @Html.DisplayFor(model => model.User.PhoneNumber)</label>
            </div>

        </div>
        <div class="form-row">
            <div class="col-md-1 mb-2"></div>
            <div class="col-md-3 mb-2">
                <p class="form-group">@Html.DisplayNameFor(model => model.User.Email)</p>
                <label class="form-group">@Html.DisplayFor(model => model.User.Email)</label>
            </div>
            <div class="col-md-3 mb-2">
                <p class="form-group">Ciudad</p>
                <label class="form-group">@Html.DisplayFor(model => model.Canton.NombreCanton)</label>
            </div>
            <div class="col-md-3 mb-2">
                <p class="form-group"> Dirección</p>
                <label class="form-group">@Html.DisplayFor(model => model.Direccion)</label>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-1 mb-2"></div>
            <div class="col-md-5 mb-2">
                <p class="form-group">Patente Municipal</p>
                <label class="form-group">@Html.DisplayFor(model => model.NumPatenteMunicipal)</label>
            </div>
            <div class="col-md-5 mb-2">
                <p class="form-group">Permiso de Funcionamiento otorgado por el MSP</p>
                <label class="form-group">@Html.DisplayFor(model => model.PermisoFuncionamientoMsp)</label>
            </div>
        </div>
        <div class="form-row ">
            <div class="form-group col-md-1 mb-3"></div>
            <div class="form-group col-md-8 mb-3"> </div>
            <div class="form-group col-md-2 mb-3">
                <a class="nav-link" asp-action="Index">Regresar</a>
            </div>
        </div>
        <br />
        <br />
    </div>

SCAME/Views/Consultorios/Edit.cshtml
@model SCAME.Models.Consultorio

@{
    ViewData["Title"] = "Editar";
}

<h2>
    Edita tu información de Consultorio
</h2>
<hr />
<div class="col-md-12">
    <form asp-action="Edit" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <input type="hidden" asp-for="UserId" />
        <input type="hidden" asp-for="IdConsultorio" />
        <input type="hidden" asp-for="ImageName" value="@Model.ImageName" />
        <div class="form-row">
            <div class="col-md-3 mb-3">
                <div class="form-group">
                    Imagen actual:
                    <img src="@("/image/" + Model.ImageName)" asp-append-version="true" class="rounded-sm" style="width:40px; height:50px" />
                </div>
                <div class="form-group">
                    <label asp-for="ImageFileNuevo" class="control-label"></label>
                    <input asp-for="ImageFileNuevo" accept="image/*" />
                    <span asp-validation-for="ImageFileNuevo" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="form-group">
                    <label asp-for="Ruc" class="control-label"></label>
                    <input asp-for="Ruc" disabled class="form-control" />
                    <span asp-validation-for="Ruc" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-3 mb-3">
                <div class="form-group">
                    <label asp-for="NombreConsultorio" class="control-label">Nombre Consultorio</label>
                    <input asp-for="NombreConsultorio" class="form-control" />
                    <span asp-validation-for="NombreConsultorio" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="form-row ">
            <div class="form-group col-md-3 mb-3">
                <label asp-for="CedulaRepresentanteLegal" class="control-label">Cédula del representate legal</label>
                <input asp-for="CedulaRepresentanteLegal" type="number" class="form-control" />
                <span asp-validation-for="CedulaRepresentanteLegal" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4 mb-3">
                <label asp-for="NombreRepresentateLegal" class="control-label">Nombres del representate legal</label>
                <input asp-for="NombreRepresentateLegal" class="form-control" />
                <span asp-validation-for="NombreRepresentateLegal" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4 mb-3">
                <label asp-for="ApellidoRepresentanteLegal" class="control-label">Apellidos del representate legal</label>
                <input asp-for="ApellidoRepresentanteLegal" class="form-control" />
                <span asp-validation-for="ApellidoRepresentanteLegal" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-2 mb-3">
                <label asp-for="CantonId" class="control-label">Selecciona tu ciudad</label>
                <select asp-for="CantonId" class="form-control" asp-items="ViewBag.CantonId"></select>
                <span asp-validation-for="CantonId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6 mb-3">
                <label asp-for="Direccion" class="control-label">Dirección</label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-5 mb-3">
                <label asp-for="NumPatenteMunicipal" class="control-label">Número de patente municipal</label>
                <input asp-for="NumPatenteMunicipal" class="form-control" />
                <span asp-validation-for="NumPatenteMunicipal" class="text-danger"></span>
            </div>
            <div class="form-group col-md-5 mb-3">
                <label asp-for="PermisoFuncionamientoMsp" class="control-label">Número del permiso de funcionamiento otrogado por MSP</label>
                <input asp-for="PermisoFuncionamientoMsp" class="form-control" />
                <span asp-validation-for="PermisoFuncionamientoMsp" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row ">
            <div class="form-group col-md-2 mb-3">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
            <div class="form-group col-md-7 mb-3"> </div>
            <div class="form-group col-md-2 mb-3">
                <a class="nav-link" asp-area="Identity" asp-page="/Account/Manage/Index">Regresar</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SCAME/Views/Consultorios/VistaComercial.cshtml
@model IEnumerable<SCAME.Models.MedicoDetalle>

@{ var modeloDetalle = this.Model.ToList();}
<br>

<div class="container">
    <div class="col-md-12 padding ">
        <div class="form-row">
            <div class="col-md-3 mb-3">
                <img src="@("/Image/" + modeloDetalle[0].Consultorio.ImageName)" asp-append-version="true" style=" width:250px; height:250px" class="foto1" />
            </div>
            <div class="col-md-8 mb-3">
                <div class="form-group">
                    <h3>Descripción</h3>
                    <p>
                        @Html.DisplayNameFor(model => model.Consultorio.NombreConsultorio): @Html.DisplayFor(model => modeloDetalle[0].Consultorio.NombreConsultorio)
                    </p>
                    <p>
                        Contacto: @Html.DisplayFor(model => modeloDetalle[0].Consultorio.User.PhoneNumber)
                    </p>
                    <p>
                        @Html.DisplayNameFor(model => modeloDetalle[0].Consultorio.User.Email): @Html.DisplayFor(model => modeloDetalle[0].Consultorio.User.Email)
                    </p>
                    <p>
                        @Html.DisplayNameFor(model => modeloDetalle[0].Consultorio.Direccion): @Html.DisplayFor(model => modeloDetalle[0].Consultorio.Direccion)
                    </p>
                </div>
                <div class="form-row ">
                    <div class="form-group col-md-6 mb-3"> </div>
                    <div class="form-group col-md-2 mb-3">
                        <a asp-controller="Citas" asp-action="Create" asp-route-idC="@modeloDetalle[0].ConsultorioId" class="btn btn-secondary text-white ">Agendar Cita</a>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <table class="table table-responsive-sm table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Medico</th>
                <th>Especialidad</th>
                <th>Precio</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var especialidad in modeloDetalle)
            {
        <tr>
            <td>@Html.DisplayFor(especialidadLista => especialidad.Medico.Apellido) @Html.DisplayFor(especialidadLista => especialidad.Medico.Nombre)</td>
            <td>@Html.DisplayFor(especialidadLista => especialidad.Especialidad.NombreEspecialidad)</td>
            <td>@Html.DisplayFor(especialidadLista => especialidad.PrecioEspecialidad)</td>

        </tr>
    }
        </tbody>
    </table>
    <br />
<br />
<br />